services:
  frontend:
    image: frontend
    container_name: frontend-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: backend
    container_name: backend-container
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    networks:
      - app-network

networks:
  app-network:
