name: Auto Label PRs and Issues with gssoc2025

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add gssoc2025 label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: gssoc2025
